# Generated by Django 3.1.2 on 2021-11-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibblebox_app', '0006_votingcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingcode',
            name='avaliable',
            field=models.BooleanField(default=True),
        ),
    ]
