# Generated by Django 3.1.2 on 2022-04-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_auto_20220428_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetails',
            name='used',
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='reference',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='verification_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
