# Generated by Django 3.1.2 on 2022-04-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0009_auto_20220428_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetails',
            name='token',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
