# Generated by Django 3.1.2 on 2022-04-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0010_shippingdetails_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetails',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
