# Generated by Django 3.1.2 on 2022-04-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0011_auto_20220430_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
