# Generated by Django 3.1.2 on 2022-04-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0012_order_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
