# Generated by Django 3.1.2 on 2022-04-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0013_auto_20220430_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='token',
        ),
    ]
