# Generated by Django 3.1.2 on 2022-04-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0014_remove_order_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetails',
            name='token',
        ),
    ]
