# Generated by Django 3.1.2 on 2022-04-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0015_remove_shippingdetails_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetails',
            name='token',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
