# Generated by Django 3.1.2 on 2022-05-01 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0019_auto_20220501_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='event',
        ),
    ]
