# Generated by Django 3.1.2 on 2022-05-01 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0021_order_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='event',
        ),
    ]
