# Generated by Django 3.1.2 on 2022-05-04 23:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0022_remove_order_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedticket',
            old_name='serial_number',
            new_name='code',
        ),
        migrations.AddField(
            model_name='purchasedticket',
            name='date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 23, 40, 8, 861339, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='purchasedticket',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Events.event'),
        ),
    ]
