# Generated by Django 3.1.2 on 2022-05-04 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0029_auto_20220504_2351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchasedTicket',
        ),
    ]
