# Generated by Django 3.1.2 on 2022-05-04 23:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0030_delete_purchasedticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('date_purchased', models.DateTimeField(default=datetime.datetime(2022, 5, 4, 23, 55, 35, 228614, tzinfo=utc))),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Events.event')),
            ],
        ),
    ]
