# Generated by Django 3.1.2 on 2022-05-05 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0031_purchasedticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedticket',
            old_name='code',
            new_name='serial_number',
        ),
        migrations.RemoveField(
            model_name='purchasedticket',
            name='date_purchased',
        ),
        migrations.RemoveField(
            model_name='purchasedticket',
            name='event',
        ),
    ]
