# Generated by Django 3.1.2 on 2022-05-05 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0033_auto_20220505_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedticket',
            name='event',
        ),
        migrations.AlterField(
            model_name='purchasedticket',
            name='date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 12, 39, 31, 806120, tzinfo=utc)),
        ),
    ]
