# Generated by Django 3.1.2 on 2022-05-05 12:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0034_auto_20220505_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedticket',
            name='date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 12, 41, 6, 826820, tzinfo=utc)),
        ),
    ]
