# Generated by Django 3.1.2 on 2022-05-05 20:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0037_auto_20220505_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedticket',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.event'),
        ),
        migrations.AlterField(
            model_name='purchasedticket',
            name='date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 20, 39, 25, 479837, tzinfo=utc)),
        ),
    ]
