# Generated by Django 3.1.2 on 2022-06-15 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0038_auto_20220505_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedticket',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchasedticket',
            name='date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 15, 8, 2, 17268, tzinfo=utc)),
        ),
    ]
