# Generated by Django 3.1.2 on 2022-06-20 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0039_auto_20220618_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedticket',
            name='date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 34, 47, 314548, tzinfo=utc)),
        ),
    ]
