# Generated by Django 3.1.2 on 2022-06-24 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0040_auto_20220617_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedticket',
            name='cost',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasedticket',
            name='date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 13, 42, 24, 642087, tzinfo=utc)),
        ),
    ]
