# Generated by Django 3.1.2 on 2022-06-25 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0042_auto_20220624_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedticket',
            name='date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 21, 3, 10, 184126, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('reg', 'regular'), ('vip', 'vip'), ('br', 'bronze'), ('au', 'gold'), ('plat', 'platanium')], max_length=70, null=True),
        ),
    ]
