# Generated by Django 4.0.6 on 2022-07-21 11:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0043_auto_20220625_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedticket',
            name='date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 11, 54, 7, 502877, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('reg', 'regular'), ('vip', 'vip'), ('br', 'bronze'), ('au', 'gold'), ('plat', 'platanium')], default='reg', max_length=70),
        ),
    ]
