# Generated by Django 4.0.6 on 2022-07-24 20:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0045_alter_purchasedticket_date_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedticket',
            name='date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 20, 0, 58, 448043, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('REGULER', 'regular'), ('VIP', 'vip'), ('BRONZE', 'bronze'), ('GOLD', 'gold'), ('PLATANIUM', 'platanium')], default='REGULAR', max_length=70),
        ),
    ]
