# Generated by Django 3.1.2 on 2022-07-01 05:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0045_auto_20220620_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedticket',
            name='date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 1, 5, 7, 26, 75794, tzinfo=utc)),
        ),
    ]
