# Generated by Django 3.1.2 on 2022-07-01 05:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0046_auto_20220701_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedticket',
            name='date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 1, 5, 33, 33, 539970, tzinfo=utc)),
        ),
    ]
