# Generated by Django 4.0.6 on 2022-07-24 22:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0046_alter_purchasedticket_date_purchased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedticket',
            name='date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 22, 38, 37, 624593, tzinfo=utc)),
        ),
    ]
