# Generated by Django 3.2.9 on 2022-07-07 04:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0050_alter_purchasedticket_date_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedticket',
            name='date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 4, 44, 17, 792642, tzinfo=utc)),
        ),
    ]
