# Generated by Django 3.2.9 on 2022-07-16 10:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0053_auto_20220716_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedticket',
            name='date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 16, 10, 43, 8, 932508, tzinfo=utc)),
        ),
    ]
