# Generated by Django 4.0.6 on 2022-07-30 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0057_alter_purchasedticket_date_purchased'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='date_published',
        ),
        migrations.AlterField(
            model_name='purchasedticket',
            name='date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 17, 1, 5, 611282, tzinfo=utc)),
        ),
    ]
