# Generated by Django 3.1.2 on 2021-10-19 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('event_image', models.ImageField(upload_to='')),
                ('event_banner', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('pg', 'pagentry'), ('aw', 'awards'), ('su', 'survey'), ('cm', 'comperism')], max_length=2)),
                ('intro_text', models.CharField(max_length=250)),
                ('discription', models.CharField(max_length=450)),
                ('date', models.DateField()),
                ('count_down', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qoute', models.CharField(max_length=250)),
                ('office', models.CharField(max_length=250)),
                ('background_image', models.ImageField(upload_to='')),
                ('personal_image', models.ImageField(upload_to='')),
                ('votes', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_candidate', to='Pageantry.event')),
            ],
        ),
    ]
