# Generated by Django 3.1.2 on 2021-10-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pageantry', '0004_auto_20211023_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='qoute',
            new_name='quote',
        ),
    ]
