# Generated by Django 3.1.2 on 2021-10-31 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pageantry', '0005_auto_20211026_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='votingCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=30)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_code', to='Pageantry.event')),
            ],
        ),
    ]
