# Generated by Django 3.1.2 on 2021-11-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pageantry', '0007_votingcode_avaliable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votingcode',
            old_name='avaliable',
            new_name='used_coupon',
        ),
    ]
