# Generated by Django 3.1.2 on 2021-11-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pageantry', '0008_auto_20211102_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingcode',
            name='used_coupon',
            field=models.BooleanField(default=False),
        ),
    ]
