# Generated by Django 3.1.2 on 2022-01-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pageantry', '0013_auto_20220104_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_of_transaction',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
