# Generated by Django 3.1.2 on 2022-01-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pageantry', '0015_auto_20220111_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
