# Generated by Django 3.1.2 on 2022-02-14 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pageantry', '0016_payment_verification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingcode',
            name='pageantry',
        ),
    ]
