# Generated by Django 3.1.2 on 2022-02-15 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pageantry', '0018_votingcode_time_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingcode',
            name='pageantry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pageantry_code', to='Pageantry.pageantry'),
        ),
    ]
