# Generated by Django 3.1.2 on 2022-02-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pageantry', '0019_votingcode_pageantry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingcode',
            name='pageantry',
        ),
    ]
