# Generated by Django 3.1.2 on 2022-02-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pageantry', '0020_remove_votingcode_pageantry'),
    ]

    operations = [
        migrations.CreateModel(
            name='couponPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_coupons', models.PositiveIntegerField()),
                ('amount', models.PositiveBigIntegerField()),
                ('verification', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_of_transaction']},
        ),
    ]
