# Generated by Django 3.1.2 on 2022-03-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pageantry', '0022_auto_20220228_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponpayment',
            name='token',
            field=models.IntegerField(null=True),
        ),
    ]
