# Generated by Django 3.1.2 on 2022-04-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pageantry', '0025_payment_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='background_image',
            field=models.ImageField(upload_to='media/candidates'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='personal_image',
            field=models.ImageField(upload_to='media/candidates'),
        ),
    ]
