# Generated by Django 4.0.6 on 2022-07-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pageantry', '0026_auto_20220419_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageantry',
            options={'ordering': ['-id']},
        ),
    ]
