# Generated by Django 4.0.6 on 2022-07-21 11:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pageantry', '0027_alter_pageantry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('slug', models.SlugField(null=True)),
                ('bio', ckeditor.fields.RichTextField(verbose_name='About yourself')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Date Joined')),
                ('d_o_b', models.DateField(null=True, verbose_name='Date of Birth')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pageantry.user')),
            ],
            options={
                'verbose_name': 'writer',
                'verbose_name_plural': 'writers',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('content', ckeditor.fields.RichTextField(null=True)),
                ('date_published', models.DateField(auto_now_add=True, verbose_name='Date Published')),
                ('last_updated', models.DateField(auto_now=True, verbose_name='Last Updated')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.writer')),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('comment', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.post')),
            ],
        ),
    ]
