# Generated by Django 3.1.2 on 2022-06-18 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('comment', models.TextField()),
                ('date_posted', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('bio', models.TextField(help_text='A short note about yourself')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Date Joined')),
            ],
            options={
                'verbose_name': 'writer',
                'verbose_name_plural': 'writers',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('text', models.TextField()),
                ('date_published', models.DateField(auto_now_add=True, verbose_name='Date Published')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.writer')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
