# Generated by Django 4.0.6 on 2022-07-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_writer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='insight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
