# Generated by Django 3.2.9 on 2022-07-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20220706_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='user',
        ),
    ]
