# Generated by Django 3.2.9 on 2022-07-06 20:16

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_remove_writer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
