# Generated by Django 3.2.9 on 2022-07-16 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pageantry', '0028_auto_20220716_1140'),
        ('Blog', '0012_auto_20220716_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pageantry.user'),
        ),
    ]
